### ISSUE TITLE
Stat area to EPU decisions

### ISSUE THREAD

**Issue by slarge** [NOAA-EDAB/mscatch#4]
Determine if necessary or not, by species. Might be facilitated with @andybeet's leaflet maps

**Comment by andybeet** [comment]
I think we can bypass this issue by ignoring stat area completely. I think we can assign landings to EPU directly provided we define the 10 min cells that make up each EPU. I don't think this will be difficult. I am testing this out using the PBSmapping package. A bit of upfront work defining the EPUs but i think painless after that. We'll see!

**Comment by slarge** [comment]
The EPU shapefiles (with estuaries) are [here](https://drive.google.com/drive/u/0/folders/1JmA1Z6rzQN949aa13cPaS5vdkWgErNox)

**Comment by andybeet** [comment]
prototype shiny app here: http://shiny1.nefsc.noaa.gov:3838/abeet/cfdbs/. Includes EPUs by 10 min square.

**Comment by andybeet** [comment]
So there are not enough trips (only about 16%) that have lat and longs associated with them. Maybe we can use the characteristics of these trips to help assign other trips to EPUs, (Very similar to what @slucey does when he assigns trips to missing AREA)

**Comment by andybeet** [comment]
mskeyrun [project](https://noaa-edab.github.io/ms-keyrun/articles/allocateLandingsEPU.html) has a method for doing this. It is being implemented as an option in [`comlandr`](https://noaa-edab.github.io/comlandr)
